{"uuid": "bce0eacf-30b5-4956-9975-6de6b5d395be", "children": ["3d6493cf-ae51-4b60-a3a0-02597d3689eb"], "befores": [{"name": "init_driver", "status": "passed", "start": 1711091450255, "stop": 1711091459861}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'testsfailed'\n", "trace": "  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\Tests\\configtest.py\", line 29, in init_driver\n    if not request.node.testsfailed:  # Check if the test failed\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1711091461723, "stop": 1711091463959}], "start": 1711091450255, "stop": 1711091463959}