{"uuid": "f035c6f2-e991-4b2c-988b-3fe0b171a545", "children": ["5bec566f-3457-42b5-ab22-10d6f49aabe8"], "befores": [{"name": "init_driver", "status": "passed", "start": 1711091856732, "stop": 1711091866146}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'testsfailed'\n", "trace": "  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\sharath.ls\\OneDrive - Feuji Software Solutions Pvt Ltd\\Documents\\Python\\PytestSeleniumlogZip\\PytestSelenium\\Tests\\configtest.py\", line 29, in init_driver\n    if not request.node.testsfailed:  # Check if the test failed\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1711091867718, "stop": 1711091870457}], "start": 1711091856732, "stop": 1711091870457}